import { addDoc, collection, doc, updateDoc } from 'firebase/firestore';
import { firestore } from '../firebase-init';

export async function createResident({
  firstName,
  middleName,
  lastName,
  dateOfBirth,
  citizenship,
  civilStatus,
  fathersName,
  mothersName,
  numberOfChildren,
  purok,
  permanentAddress,
  occupation,
  phoneNumber,
  religion,
  sex,
  spouse,
  status,
  tribe,
  weight,
  height,
  collegeAddress,
  collegeSchool,
  collegeYearGrad,
  elementaryAddress,
  elementarySchool,
  elementaryYearGrad,
  fathersAddress,
  fathersOccupation,
  highschoolAddress,
  highschoolName,
  highschoolYearGrad,
  mothersAddress,
  mothersOccupation,
  spouseAddress,
  vocationalAddress,
  vocationalSchool,
  vocationalYearGrad,
}) {
  console.log({
    firstName,
    middleName,
    lastName,
    dateOfBirth,
    citizenship,
    civilStatus,
    fathersName,
    mothersName,
    numberOfChildren,
    occupation,
    permanentAddress,
    phoneNumber,
    religion,
    sex,
    spouse,
    status,
    tribe,
    purok,
    weight,
    height,
    collegeAddress,
    collegeSchool,
    collegeYearGrad,
    elementaryAddress,
    elementarySchool,
    elementaryYearGrad,
    fathersAddress,
    fathersOccupation,
    highschoolAddress,
    highschoolName,
    highschoolYearGrad,
    mothersAddress,
    mothersOccupation,
    spouseAddress,
    vocationalAddress,
    vocationalSchool,
    vocationalYearGrad,
  });
  return addDoc(collection(firestore, 'resident'), {
    firstName,
    middleName,
    lastName,
    dateOfBirth,
    citizenship,
    civilStatus,
    fathersName,
    mothersName,
    numberOfChildren,
    permanentAddress,
    occupation,
    phoneNumber,
    religion,
    sex,
    spouse,
    status,
    tribe,
    purok,
    weight,
    height,
    collegeAddress,
    collegeSchool,
    collegeYearGrad,
    elementaryAddress,
    elementarySchool,
    elementaryYearGrad,
    fathersAddress,
    fathersOccupation,
    highschoolAddress,
    highschoolName,
    highschoolYearGrad,
    mothersAddress,
    mothersOccupation,
    spouseAddress,
    vocationalAddress,
    vocationalSchool,
    vocationalYearGrad,
  }).then((res) => {
    console.log({ res });
    return res;
  });
}

export function updateResident(uid, data) {
  const residentRef = doc(firestore, `resident/${uid}`);

  return updateDoc(residentRef, data);
}
